// db-modeler-react/src/pages/ProjectList/index.tsx
import React, { useState } from "react";
import {
  Card,
  Button,
  Table,
  Space,
  Modal,
  Form,
  Input,
  message,
  Typography,
} from "antd";
import {
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
} from "@ant-design/icons";
import { useNavigate } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import { addProject, updateProject } from "../../store/projectSlice";
import { v4 as uuidv4 } from "uuid";
import type { RootState } from "../../main";

interface Project {
  id: string;
  name: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

const { Title } = Typography;

export const ProjectList: React.FC = () => {
  const navigate = useNavigate();
  const dispatch = useDispatch();
  const projects = useSelector((state: RootState) => state.projects.projects);
  const loading = useSelector((state: RootState) => state.projects.loading);

  const [isModalVisible, setIsModalVisible] = useState(false);
  const [form] = Form.useForm();
  const [editingId, setEditingId] = useState<string | null>(null);

  const columns = [
    {
      title: "项目名称",
      dataIndex: "name",
      key: "name",
    },
    {
      title: "描述",
      dataIndex: "description",
      key: "description",
    },
    {
      title: "创建时间",
      dataIndex: "createdAt",
      key: "createdAt",
    },
    {
      title: "更新时间",
      dataIndex: "updatedAt",
      key: "updatedAt",
    },
    {
      title: "操作",
      key: "action",
      render: (_: unknown, record: Project) => (
        <Space size="middle">
          <Button
            type="link"
            icon={<EditOutlined />}
            onClick={(e) => {
              e.stopPropagation();
              handleEdit(record);
            }}
          >
            编辑
          </Button>
          <Button
            type="link"
            danger
            icon={<DeleteOutlined />}
            onClick={(e) => {
              e.stopPropagation();
              handleDelete(record.id);
            }}
          >
            删除
          </Button>
        </Space>
      ),
    },
  ];

  const handleAdd = () => {
    setEditingId(null);
    form.resetFields();
    setIsModalVisible(true);
  };

  const handleEdit = (record: Project) => {
    setEditingId(record.id);
    form.setFieldsValue(record);
    setIsModalVisible(true);
  };

  const handleDelete = (id: string) => {
    Modal.confirm({
      title: "确认删除",
      content: "确定要删除这个项目吗？",
      onOk() {
        // dispatch(deleteProject(id));
        message.success("删除成功");
      },
    });
  };

  const handleModalOk = async () => {
    try {
      const values = await form.validateFields();
      const now = new Date().toISOString();
      if (editingId) {
        dispatch(
          updateProject({
            ...values,
            id: editingId,
            updatedAt: now,
          })
        );
        message.success("更新成功");
      } else {
        dispatch(
          addProject({
            ...values,
            id: uuidv4(),
            createdAt: now,
            updatedAt: now,
          })
        );
        message.success("创建成功");
      }
      setIsModalVisible(false);
      form.resetFields();
    } catch (error) {
      console.error("Validate Failed:", error);
    }
  };

  return (
    <div style={{ padding: "24px" }}>
      <Card>
        <div style={{ marginBottom: "16px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <Title level={4} style={{ margin: 0 }}>项目列表</Title>
          <Button
            type="primary"
            icon={<PlusOutlined />}
            onClick={handleAdd}
          >
            新建项目
          </Button>
        </div>
        <Table<Project>
          columns={columns}
          dataSource={projects}
          rowKey="id"
          loading={loading}
          onRow={(record) => ({
            onClick: () => navigate(`/project/${record.id}`),
          })}
        />
      </Card>

      <Modal
        title={editingId ? "编辑项目" : "新建项目"}
        open={isModalVisible}
        onOk={handleModalOk}
        onCancel={() => {
          setIsModalVisible(false);
          form.resetFields();
        }}
      >
        <Form
          form={form}
          layout="vertical"
        >
          <Form.Item
            name="name"
            label="项目名称"
            rules={[{ required: true, message: "请输入项目名称" }]}
          >
            <Input />
          </Form.Item>
          <Form.Item
            name="description"
            label="描述"
          >
            <Input.TextArea />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

// db-modeler-ui/src/components/ProjectList.vue
<template>
  <div class="project-list">
    <div class="project-header">
      <h2>项目列表</h2>
      <a-button type="primary" @click="showCreateModal">新建项目</a-button>
    </div>

    <a-table
      :columns="columns"
      :data-source="projects"
      :loading="loading"
      row-key="id"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'action'">
          <a-space>
            <a-button type="link" @click="handleEdit(record)">编辑</a-button>
            <a-popconfirm
              title="确定要删除这个项目吗？"
              @confirm="handleDelete(record.id)"
            >
              <a-button type="link" danger>删除</a-button>
            </a-popconfirm>
          </a-space>
        </template>
      </template>
    </a-table>

    <a-modal
      v-model:visible="modalVisible"
      :title="modalMode === 'create' ? '新建项目' : '编辑项目'"
      @ok="handleModalOk"
    >
      <a-form
        ref="formRef"
        :model="formState"
        :rules="rules"
        layout="vertical"
      >
        <a-form-item label="项目名称" name="name">
          <a-input v-model:value="formState.name" />
        </a-form-item>
        <a-form-item label="项目描述" name="description">
          <a-textarea v-model:value="formState.description" />
        </a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<script lang="ts" setup>
import { ref, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import type { Project } from '../api/project'
import { projectApi } from '../api/project'
import { useGlobalStore } from '../stores/global'

const globalStore = useGlobalStore()

const columns = [
  {
    title: '项目名称',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: '描述',
    dataIndex: 'description',
    key: 'description',
  },
  {
    title: '创建时间',
    dataIndex: 'createdAt',
    key: 'createdAt',
  },
  {
    title: '操作',
    key: 'action',
  },
]

const projects = ref<Project[]>([])
const loading = ref(false)
const modalVisible = ref(false)
const modalMode = ref<'create' | 'edit'>('create')
const formState = ref({
  name: '',
  description: '',
  tenantId: globalStore.currentTenant?.id
})

const rules = {
  name: [{ required: true, message: '请输入项目名称' }],
}

const loadProjects = async () => {
  if (!globalStore.currentTenant?.id) {
    message.error('请先选择租户')
    return
  }
  loading.value = true
  try {
    const response = await projectApi.getProjects(globalStore.currentTenant.id)
    projects.value = response.data
  } catch (error) {
    message.error('加载项目列表失败')
  } finally {
    loading.value = false
  }
}

const showCreateModal = () => {
  if (!globalStore.currentTenant?.id) {
    message.error('请先选择租户')
    return
  }
  modalMode.value = 'create'
  formState.value = {
    name: '',
    description: '',
    tenantId: globalStore.currentTenant.id
  }
  modalVisible.value = true
}

const handleEdit = (record: Project) => {
  modalMode.value = 'edit'
  formState.value = {
    name: record.name,
    description: record.description,
    tenantId: record.tenantId,
  }
  modalVisible.value = true
}

const handleDelete = async (id: string) => {
  try {
    await projectApi.deleteProject(id)
    message.success('删除成功')
    loadProjects()
  } catch (error) {
    message.error('删除失败')
  }
}

const handleModalOk = async () => {
  try {
    if (modalMode.value === 'create') {
      await projectApi.createProject(formState.value)
      message.success('创建成功')
    } else {
      // await projectApi.updateProject(currentId, formState.value)
      message.success('更新成功')
    }
    modalVisible.value = false
    loadProjects()
  } catch (error) {
    message.error(modalMode.value === 'create' ? '创建失败' : '更新失败')
  }
}

onMounted(() => {
  loadProjects()
})
</script>

<style scoped>
.project-list {
  padding: 24px;
}

.project-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
}

.project-header h2 {
  margin: 0;
}
</style>
